"""Initial Migration

Revision ID: 185928322077
Revises: 5546640aa947
Create Date: 2020-05-02 11:30:28.604138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185928322077'
down_revision = '5546640aa947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downvotes', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('downvotes_pitch_id_fkey', 'downvotes', type_='foreignkey')
    op.create_foreign_key(None, 'downvotes', 'posts', ['post_id'], ['id'])
    op.drop_column('downvotes', 'pitch_id')
    op.alter_column('posts', 'en_body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('upvotes', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('upvotes_pitch_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'posts', ['post_id'], ['id'])
    op.drop_column('upvotes', 'pitch_id')
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'image_file')
    op.drop_column('users', 'email')
    op.add_column('upvotes', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_pitch_id_fkey', 'upvotes', 'posts', ['pitch_id'], ['id'])
    op.drop_column('upvotes', 'post_id')
    op.alter_column('posts', 'en_body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('downvotes', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.create_foreign_key('downvotes_pitch_id_fkey', 'downvotes', 'posts', ['pitch_id'], ['id'])
    op.drop_column('downvotes', 'post_id')
    # ### end Alembic commands ###
