"""Initial Migration

Revision ID: 53d6ab1f38ad
Revises: 92b821cf9759
Create Date: 2020-05-02 02:19:01.755763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d6ab1f38ad'
down_revision = '92b821cf9759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('user_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('posts', 'de_url')
    op.drop_column('posts', 'de_title')
    op.drop_column('posts', 'de_subtitle')
    op.drop_column('posts', 'de_description')
    op.drop_column('posts', 'de_body')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'username')
    op.add_column('posts', sa.Column('de_body', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('de_description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('de_subtitle', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('de_title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('de_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_table('comments')
    # ### end Alembic commands ###
